### PR TITLE
allow multiple copies of the same slider

### PR DESCRIPTION
**Pull request by Tymvie**
For example, on this page there are  multiple copies of the same slider: http://ads.webgilde.com/test-slider-and-page-ads/

### CODE REVIEW

**Comment by webzunft** [comment]
@Tymvie I agree that having multiple same ids if the same slider is on a page is not great.
However, a random ID is not good, because people might actually want to create additional css rules, so we need a static identifier.
I also kept it this way, because I actually never saw one site having the same slider multiple times on one page.
Does it cause issues on our own test page?

**Comment by Tymvie** [comment]
@webzunft no, I can assign different ids when I test

**Comment by webzunft** [comment]
@Tymvie so, technically it would ok to leave it without the fix?

**Comment by Tymvie** [comment]
@webzunft it is ok only if the page will contain not more than one slider.
If the second slider with the same id will be initialized after the first slider, then the first slider will stop working correctly

**Comment by webzunft** [comment]
You could add the specific, static identifier (the one you removed) as a class. This should solve the issue targeting the slider with css and fix multiple sliders on the same page.

**Comment by Tymvie** [comment]
@webzunft ok, i added these pull-requests:
https://github.com/webgilde/advanced-ads-slider/pull/8
https://github.com/webgilde/advanced-ads-pro/pull/169

**Pull request closed without merging**
